################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32H7xx_HAL_Driver/Src \
Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src \
Middlewares/ST/STM32_USB_Device_Library/Core/Src \
TouchGFX/App \
TouchGFX/build/MINGW32_NT-6.2/generated/fonts/src \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/accueil_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/common \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/configuration_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/containers \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/courbe_loi_d_eau_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/energies_cumul_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/energies_histo_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/energies_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/erreurs_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/historiques_fonctionnement_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/infos_systeme_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_circuit_captage_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_circuit_primaire_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_config_hydrau_rapide_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_ecs_avances_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_ecs_cycle_legionel_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_ecs_simultane_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/installation_hysteresis_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/maintenance_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/multizones_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/page_oui_non_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/piscine_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/programmation_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/programmation_zoom_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/synoptique_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/test_pac_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/usine_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/vacances_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/variables_systeme_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src \
TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src \
TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src/video \
TouchGFX/build/MINGW32_NT-6.2/generated/texts/src \
TouchGFX/build/MINGW32_NT-6.2/gui/src/accueil_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/common \
TouchGFX/build/MINGW32_NT-6.2/gui/src/configuration_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/containers \
TouchGFX/build/MINGW32_NT-6.2/gui/src/courbe_loi_d_eau_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/energies_cumul_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/energies_histo_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/energies_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/erreurs_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/historiques_fonctionnement_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/infos_systeme_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_circuit_captage_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_circuit_primaire_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_config_hydrau_rapide_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_ecs_avances_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_ecs_cycle_legionel_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_ecs_simultane_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/installation_hysteresis_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/maintenance_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/model \
TouchGFX/build/MINGW32_NT-6.2/gui/src/multizones_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/page_oui_non_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/piscine_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/programmation_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/programmation_zoom_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/synoptique_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/test_pac_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/usine_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/vacances_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/variables_systeme_screen \
TouchGFX/build/MINGW32_NT-6.2/simulator \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/driver/touch \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/hal/simulator/sdl2 \
TouchGFX/generated/fonts/src \
TouchGFX/generated/gui_generated/src/common \
TouchGFX/generated/gui_generated/src/containers \
TouchGFX/generated/gui_generated/src/screen1_screen \
TouchGFX/generated/images/src \
TouchGFX/generated/texts/src \
TouchGFX/gui/src/common \
TouchGFX/gui/src/containers \
TouchGFX/gui/src/model \
TouchGFX/gui/src/screen1_screen \
TouchGFX/target \
TouchGFX/target/generated \
USB_DEVICE/App \
USB_DEVICE/Target \

